"""TATTOOS (2026-10-04, homestead/tattoo/Tattoos): the 12 pirate tattoo designs as player-model overlays + screen icons.

    python tools/gen_tattoo_textures.py

Each design is 16x16 pixel art (the grids below). The game draws a tattoo by rendering the player model a second time with
a mostly transparent 256x256 overlay (4x the 64x64 skin, so a skin pixel = 4x4 texels): the design sits on the outer side
of an upper arm (16 texels wide = one 4-pixel arm face, at 1x) or on the chest / back (doubled to 32x32). Writes
textures/entity/tattoo/<design>_<slot>.png (slots right_arm, left_arm, left_arm_slim, chest, back), textures/gui/tattoo/
<design>.png (32x32 icons) and tools/previews/tattoos.png. Ids must match Tattoos.DESIGNS.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
TEX = ROOT / "src/main/resources/assets/pixelpirates/textures"
PREV = ROOT / "tools/previews/tattoos.png"

INK = {"k": (24, 30, 52), "r": (168, 34, 40), "g": (40, 112, 64), "y": (214, 172, 52), "b": (44, 86, 160),
       "w": (236, 232, 220), "p": (196, 98, 132), "o": (204, 112, 40), "t": (40, 128, 128)}
ALPHA = 225                      # ink sits in the skin, not on it

DESIGNS = {
    "anchor": [
        "......kkkk......",
        ".....k....k.....",
        ".....k....k.....",
        "......kkkk......",
        ".......kk.......",
        "...kkkkkkkkkk...",
        ".......kk.......",
        ".......kk.......",
        ".......kk.......",
        ".......kk.......",
        ".k.....kk.....k.",
        "kkk....kk....kkk",
        ".kk....kk....kk.",
        "..kk...kk...kk..",
        "...kkkkkkkkkk...",
        ".....kkkkkk.....",
    ],
    "skull_crossbones": [
        "k..............k",
        ".k....kkkk....k.",
        "..k.kkwwwwkk.k..",
        "...kwwwwwwwwk...",
        "...kwwwwwwwwk...",
        "...kwkkwwkkwk...",
        "...kwkkwwkkwk...",
        "...kwwwkkwwwk...",
        "....kwwwwwwk....",
        ".....kwkwkk.....",
        "....k.kkkk.k....",
        "...k........k...",
        "..k..........k..",
        ".kw..........wk.",
        "kww..........wwk",
        ".k............k.",
    ],
    "swallow": [
        "................",
        "...kk...........",
        "..kbbk..........",
        "..kbbbk.........",
        "...kbbbk....kk..",
        "....kbbbkkkkbbk.",
        ".....kbbbbbbbk..",
        "....kkrrbbbbk...",
        "...krrrrrbbk....",
        "..kwwrrrrkk.....",
        "..kwwwwwk.bk....",
        "...kkwwk..kbk...",
        ".....kk....kbk..",
        "............kbk.",
        ".............kk.",
        "................",
    ],
    "rose": [
        "................",
        ".....kkkkkk.....",
        "....krrrrrrk....",
        "...krrkkkrrrk...",
        "...krkrrrkrrk...",
        "...krkrkkrkrk...",
        "...krrkrrkrrk...",
        "....krrkkrrk....",
        ".....kkrrkk.....",
        "...kk..kk..kk...",
        "..kggk.kg.kggk..",
        "...kgggkgkggk...",
        ".......kg.......",
        ".......kg.......",
        "......kg........",
        "......kg........",
    ],
    "compass": [
        ".......kk.......",
        ".......kk.......",
        ".....kkrrkk.....",
        "....k..rr..k....",
        "...k...rr...k...",
        "..k...krrk...k..",
        "..k..kkkkkk..k..",
        "kkkkkkkwwkkkkkkk",
        "kkkkkkkwwkkkkkkk",
        "..k..kkkkkk..k..",
        "..k...kbbk...k..",
        "...k...bb...k...",
        "....k..bb..k....",
        ".....kkbbkk.....",
        ".......kk.......",
        ".......kk.......",
    ],
    "mermaid": [
        "......kk........",
        ".....kyyk.......",
        "....kyyyyk......",
        "....kypyyk......",
        "....kyppyk......",
        ".....kppk.......",
        "....kpppk.......",
        "...kp.pp.k......",
        ".....kppk.......",
        ".....ktttk......",
        "......ktttk.....",
        ".......ktttk....",
        "........kttk....",
        "........kttk.k..",
        ".........ktktk..",
        "..........kkk...",
    ],
    "ship": [
        ".......k........",
        "......kwk.......",
        ".....kwwk.......",
        "....kwwwk..k....",
        "...kwwwwk.kwk...",
        "..kwwwwwkkwwk...",
        "...kkkkkkkkkk...",
        "......k..k......",
        ".kkkkkkkkkkkkkk.",
        ".kooooooooooook.",
        "..kooooooooook..",
        "...kkkkkkkkkk...",
        "..b..b..b..b..b.",
        ".b.bb.bb.bb.bb..",
        "................",
        "................",
    ],
    "sweetheart": [
        "................",
        "...kkk....kkk...",
        "..krrrk..krrrk..",
        ".krrrrrkkrrrrrk.",
        ".krrrrrrrrrrrrk.",
        ".krrrrrrrrrrrrk.",
        "kkkkkkkkkkkkkkkk",
        "kwwwwwwwwwwwwwwk",
        "kkkkkkkkkkkkkkkk",
        "...krrrrrrrrk...",
        "....krrrrrrk....",
        ".....krrrrk.....",
        "......krrk......",
        ".......kk.......",
        "................",
        "................",
    ],
    "dagger": [
        ".......kk.......",
        "......kyyk......",
        ".......kk.......",
        ".......kk.......",
        "....kkkkkkkk....",
        "....kyyyyyyk....",
        "....kkkkkkkk....",
        "......kwwk......",
        "......kwwk......",
        "......kwwk......",
        "......kwwk......",
        "......kwwk......",
        ".......kwk......",
        ".......kwk......",
        "........k.......",
        "....r.....r.....",
    ],
    "jolly_roger": [
        "k...............",
        "kkkkkkkkkkkkkkk.",
        "kkkkkkkkkkkkkkk.",
        "kkkkkkwwwwkkkkk.",
        "kkkkkwwwwwwkkkk.",
        "kkkkkwkwwkwkkkk.",
        "kkkkkwwwwwwkkkk.",
        "kkkkkkwkkwkkkkk.",
        "kkkwkkkkkkkkwkk.",
        "kkkkwwkkkkwwkkk.",
        "kkkkkkwwwwkkkkk.",
        "kkkkwwkkkkwwkkk.",
        "kkkwkkkkkkkkwkk.",
        "kkkkkkkkkkkkkkk.",
        "k...............",
        "k...............",
    ],
    "sea_serpent": [
        "................",
        "..kkk...........",
        ".kgggk..........",
        "kgkggrk.........",
        "kgggk.k.........",
        ".kgk............",
        "..kgk.....kkk...",
        "...kgk...kgggk..",
        "....kgk.kgk.kgk.",
        ".....kgkgk...kgk",
        "......kgk.....kk",
        "..........kk..k.",
        "bb.bb.bb.kggkk..",
        ".bb.bb.bb.kk....",
        "................",
        "................",
    ],
    "kraken": [
        ".....kkkkkk.....",
        "....kppppppk....",
        "...kppppppppk...",
        "...kpkkppkkpk...",
        "...kpkwppkwpk...",
        "...kppppppppk...",
        "....kppppppk....",
        "...kpkpkpkpkpk..",
        "..kpk.kp.kp.kpk.",
        ".kpk.kpk.kpk.kp.",
        ".kp..kp...kp..kp",
        "kpk.kpk...kpk.kk",
        "kp..kp.....kp...",
        "kk..kpk....kpk..",
        "....kk......kk..",
        "................",
    ],
    "shark": [
        "................",
        "......k.........",
        ".....kbk........",
        "....kbbk........",
        "...kbbbbkkkkk...",
        "..kbbbbbbbbbbk.k",
        ".kbkbbbbbbbbbbkk",
        "kbbbbbbbbbbbbbbk",
        "kwwwwbbbbbbbbbkk",
        ".kwkwkwwwwwbbk.k",
        "..kkkkkwwwkbk...",
        ".......kkk.kk...",
        "................",
        "................",
        "................",
        "................",
    ],
    "crossed_cutlasses": [
        "k..............k",
        ".kw..........wk.",
        "..kw........wk..",
        "...kw......wk...",
        "....kw....wk....",
        ".....kw..wk.....",
        "......kwwk......",
        ".......kk.......",
        "......kwwk......",
        ".....kykkyk.....",
        "....kyk..kyk....",
        "...kkk....kkk...",
        "..kyk......kyk..",
        ".kyk........kyk.",
        ".kk..........kk.",
        "................",
    ],
    "treasure_chest": [
        "................",
        "................",
        "...kkkkkkkkkk...",
        "..koooooooooook.",
        "..koooooooooook.",
        "..kkkkkkkkkkkkk.",
        "..kyyyyyyyyyyyk.",
        "..kkkkkykkkkkkk.",
        "..kooookykooook.",
        "..kooooykyooook.",
        "..kooooookooook.",
        "..kkkkkkkkkkkkk.",
        "..y.y..y..y.y...",
        ".y.y.yy.yy.y.y..",
        "................",
        "................",
    ],
    "parrot": [
        "......kkk.......",
        ".....krrrk......",
        "....krrkrk......",
        "....krrrrkk.....",
        "....krrrkyyk....",
        "....krrrrkkk....",
        "...kbrrrrk......",
        "..kbbbrrrk......",
        "..kbbbyrrk......",
        "..kbbyyrk.......",
        "...kbyyk........",
        "....kgk.........",
        "....kgk.........",
        "...kgk..........",
        "...kk...........",
        "................",
    ],
    "nautical_star": [
        ".......kk.......",
        ".......kk.......",
        "......krbk......",
        "......krbk......",
        "kkk..krrbbk..kkk",
        ".kbbkrrrbbbkrrk.",
        "..kbbbbrbbrrrk..",
        "...kbbbbrrrrk...",
        "...krrrrbbbbk...",
        "..krrrbbrbbbbk..",
        ".krrkbbbrrrkbbk.",
        "kkk..kbbrrk..kkk",
        "......kbrk......",
        "......kbrk......",
        ".......kk.......",
        ".......kk.......",
    ],
    "lighthouse": [
        "...y...kk...y...",
        "....y.kyyk.y....",
        ".......kk.......",
        "......kkkk......",
        "......kwwk......",
        "......krrk......",
        ".....kwwwwk.....",
        ".....krrrrk.....",
        ".....kwwwwk.....",
        "....krrrrrrk....",
        "....kwwwwwwk....",
        "...kkkkkkkkkk...",
        "..b..b..b..b..b.",
        ".b.bb.bb.bb.bb..",
        "................",
        "................",
    ],
    "rum_bottle": [
        "......kk........",
        "......kk........",
        ".....kook.......",
        ".....kggk.......",
        ".....kggk.......",
        "....kggggk......",
        "...kggggggk.....",
        "...kgwwwwgk.....",
        "...kgwkkwgk.....",
        "...kgwwwwgk.....",
        "...kggggggk.....",
        "...kggggggk.....",
        "....kkkkkk......",
        "................",
        "................",
        "................",
    ],
    "sea_turtle": [
        "................",
        "......kkk.......",
        ".....kgggk......",
        "..k..kgkgk..k...",
        ".kgk.kgggk.kgk..",
        "..kgkkkkkkkgk...",
        "...kggogoggk....",
        "...kgogggogk....",
        "...kgggoggg.k...",
        "...kgogggogk....",
        "..kgkggoggkgk...",
        ".kgk.kkkkk.kgk..",
        "..k...kgk...k...",
        ".......k........",
        "................",
        "................",
    ],
    "ghost_ship": [
        "................",
        "......t.........",
        ".....twt...t....",
        "....twwt..twt...",
        "...twwwt.twwt...",
        "..twwwwttwwwt...",
        "...tttttttttt...",
        ".......t........",
        ".tttttttttttttt.",
        ".tkkkkkkkkkkkkt.",
        "..tkk.kk.kkkkt..",
        "...tttttttttt...",
        "..t..t..t..t..t.",
        ".t.tt.tt.tt.tt..",
        "................",
        "................",
    ],
    "leviathan": [
        "................",
        "..kkkk..........",
        ".kttttk.........",
        "kttwkttk........",
        "ktttttttkk......",
        ".kwkwkwttk......",
        "..kkkkkttk...kk.",
        "......kttk..kttk",
        "......kttk.ktk..",
        ".....kttk..ktk..",
        "....kttk..kttk..",
        "...kttk..kttk...",
        "..kttkkkkttk....",
        "..kttttttttk....",
        "...kkkkkkkk.....",
        "................",
    ],
}


def art(name):
    grid = DESIGNS[name]
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y, row in enumerate(grid):
        for x, ch in enumerate(row.ljust(16, ".")[:16]):
            if ch in INK:
                im.putpixel((x, y), INK[ch] + (ALPHA,))
    return im


# overlay placement on the 256x256 sheet (4x the skin): (x, y, scale) of the design's top-left
SLOTS = {
    "right_arm": (160, 108, 1),         # right arm, outer side face (skin u40..44, v20..32), the forearm (bare on most skins)
    "left_arm": (160, 236, 1),          # left arm, outer side face, wide arms (skin u40..44, v52..64)
    "left_arm_slim": (156, 236, 1),     # ...slim arms (skin u39..43)
    "chest": (80, 84, 2),               # body front (skin u20..28, v20..32)
    "back": (128, 84, 2),               # body back (skin u32..40)
}


def main():
    (TEX / "entity/tattoo").mkdir(parents=True, exist_ok=True)
    (TEX / "gui/tattoo").mkdir(parents=True, exist_ok=True)
    sheet = Image.new("RGBA", (16 * 2 * len(DESIGNS) + 8 * len(DESIGNS), 40), (226, 190, 160, 255))
    for i, name in enumerate(DESIGNS):
        a = art(name)
        for slot, (x, y, s) in SLOTS.items():
            ov = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
            ov.alpha_composite(a.resize((16 * s, 16 * s), Image.NEAREST), (x, y))
            ov.save(TEX / f"entity/tattoo/{name}_{slot}.png")
        icon = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
        icon.alpha_composite(a.resize((32, 32), Image.NEAREST), (0, 0))
        icon.save(TEX / f"gui/tattoo/{name}.png")
        sheet.alpha_composite(a.resize((32, 32), Image.NEAREST), (4 + i * 40, 4))
    PREV.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(PREV)
    print("tattoos:", len(DESIGNS), "x", len(SLOTS), "overlays ->", TEX / "entity/tattoo")


if __name__ == "__main__":
    main()
