"""The Galley (2026-09-30): item textures + English names for every dish in item/food/PirateFoods.java.

    python tools/gen_food_textures.py          -> textures/item/<id>.png, lang entries, tools/previews/food_sheet.png

Each dish = a TEMPLATE (16x16 char grid: bowl, bottle, skewer, pie, slice, cookie, plate, fillet, taco, jerky,
crisps, pudding) + a palette, drawn by gen_overhaul_textures.sprite() (top-left lighting + dark outline), so they
match the rest of the mod's icons. Ids must match PirateFoods.
"""
import json, collections, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import gen_overhaul_textures as g
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANG = ROOT / "src/main/resources/assets/pixelpirates/lang/en_us.json"

T = {
    "bowl": [
        "................",
        "................",
        "................",
        "................",
        ".......g........",
        "....ffgfffg.....",
        "...fffffffff....",
        "..wwwwwwwwwwww..",
        "..wfffffffffgw..",
        "...wwwwwwwwww...",
        "...wwwwwwwwww...",
        "....wwwwwwww....",
        ".....wwwwww.....",
        "................",
        "................",
        "................"],
    "bottle": [
        "................",
        "......cc........",
        "......cc........",
        ".....gggg.......",
        "......gg........",
        ".....gllg.......",
        "....glllhg......",
        "...glllllhg.....",
        "...gllllllg.....",
        "...gllllllg.....",
        "...gllllllg.....",
        "....gllllg......",
        ".....gggg.......",
        "................",
        "................",
        "................"],
    "jar": [
        "................",
        "................",
        ".....cccc.......",
        ".....gggg.......",
        "....glldlg......",
        "....gdlldg......",
        "....glldlg......",
        "....gdlldg......",
        "....gldllg......",
        "....glldlg......",
        ".....gggg.......",
        "................",
        "................",
        "................",
        "................",
        "................"],
    "skewer": [
        "................",
        "..............s.",
        ".............s..",
        "..........aas...",
        ".........aAas...",
        "........bbas....",
        ".......bBbs.....",
        "......aabb......",
        ".....aAsa.......",
        "....bbsb........",
        "...bBs..........",
        "...ss...........",
        "..s.............",
        ".s..............",
        "................",
        "................"],
    "pie": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "....cccccccc....",
        "..ccffffffffcc..",
        ".cfffftffftfffc.",
        ".cffffffffffffc.",
        ".cccccccccccccc.",
        "..cCCCCCCCCCCc..",
        "................",
        "................",
        "................",
        "................",
        "................"],
    "slice": [
        "................",
        "................",
        "................",
        "................",
        "...........tt...",
        ".........ttttt..",
        ".......tttttttt.",
        ".....ttttttttttt",
        "...aaaaaaaaaaaaa",
        "...fffffffffffff",
        "...aaaaaaaaaaaaa",
        "...aaaaaaaaaaaaa",
        "................",
        "................",
        "................",
        "................"],
    "cookie": [
        "................",
        "................",
        "................",
        "................",
        ".....cccccc.....",
        "....ccdccccc....",
        "...ccccccdccc...",
        "...cdcccccccc...",
        "...ccccdccccc...",
        "...cccccccdcc...",
        "....ccdccccc....",
        ".....cccccc.....",
        "................",
        "................",
        "................",
        "................"],
    "cakes": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "........cccc....",
        ".......cdccdc...",
        "...cccccccccc...",
        "..cdccdccdccc...",
        "..cccccccccc....",
        "..cccccdccc.....",
        "...ccccccc......",
        "................",
        "................",
        "................",
        "................"],
    "plate": [
        "................",
        "................",
        "................",
        "................",
        "................",
        ".....aaaab......",
        "...aaAaaabbb....",
        "...aaaaaabbBb...",
        "..pppppppppppp..",
        ".pPPPPPPPPPPPPp.",
        "..pppppppppppp..",
        "................",
        "................",
        "................",
        "................",
        "................"],
    "fillet": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "......aaaaaa....",
        "....aaAbaabaa...",
        "...aAaaaabaaaa..",
        "..aaaabaaaaabaa.",
        "...aaaaaabaaaa..",
        "....aabaaaaaa...",
        "......aaaaa.....",
        "................",
        "................",
        "................",
        "................"],
    "taco": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "......bcbc......",
        "....bcbbcbcb....",
        "...aabcbbcbaa...",
        "..aAaaaaaaaaaa..",
        "..aaaaaaaaaaaa..",
        "...aaaaaaaaaa...",
        ".....aaaaaa.....",
        "................",
        "................",
        "................",
        "................"],
    "jerky": [
        "................",
        "................",
        "................",
        "................",
        "..........aa....",
        ".........aAba...",
        "........abaa....",
        ".....bbabaa.....",
        "....bBbaaa......",
        "...bbabb........",
        "..bbbbb.........",
        "..bbb...........",
        "................",
        "................",
        "................",
        "................"],
    "crisps": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "........aaa.....",
        "...aaa.aAaaa....",
        "..aAaaaaaa.aaa..",
        "..aaaaa..aaaAa..",
        "...aaa.aaa.aaa..",
        ".....aaAaa......",
        "......aaa.......",
        "................",
        "................",
        "................",
        "................"],
    "pudding": [
        "................",
        "................",
        "................",
        "................",
        ".......tt.......",
        ".....cctcc......",
        "....cccccccc....",
        "...caccacccac...",
        "...cccccaccc....",
        "...caccccccac...",
        "...ccacccaccc...",
        "..pppppppppppp..",
        "...pPPPPPPPPp...",
        "................",
        "................",
        "................"],
}

R = g.ramp
BOWL = R("#8a5a30")
GLASS = R("#b8d8e0", 1.1, 0.75)
CORK = R("#8a6a42")
PLATE = R("#e8e4dc")
STICK = R("#8a6a42")
CRUST = R("#c89a5a")

# id: (template, palette, flat, name)
DISHES = {
    "banana_fritters": ("cakes", {"c": R("#d8a040"), "d": R("#f6e27a")}, "d", "Banana Fritters"),
    "banana_pudding": ("bowl", {"w": BOWL, "f": R("#f0dc8a"), "g": R("#e8c83a")}, "g", "Banana Pudding"),
    "coconut_macaroon": ("cookie", {"c": R("#f2ead8"), "d": R("#b88a5a")}, "d", "Coconut Macaroon"),
    "coconut_cream_pie": ("pie", {"c": CRUST, "C": R("#a8783a"), "f": R("#fbf6ea"), "t": R("#8a6040")}, "t", "Coconut Cream Pie"),
    "seaweed_salad": ("bowl", {"w": BOWL, "f": R("#3a7a3a"), "g": R("#c83a4a")}, "g", "Seaweed Salad"),
    "kelp_crisps": ("crisps", {"a": R("#4a6a2a"), "A": R("#7a9a4a")}, "A", "Kelp Crisps"),
    "plum_duff": ("pudding", {"c": R("#8a4a2a"), "a": R("#5a1a2a"), "t": R("#f0ead8"), "p": PLATE, "P": R("#c8c4bc")}, "t", "Plum Duff"),
    "biscuit_porridge": ("bowl", {"w": BOWL, "f": R("#e8dcc0"), "g": R("#c4a46a")}, "g", "Biscuit Porridge"),
    "tropical_smoothie": ("bottle", {"g": GLASS, "c": CORK, "l": R("#f0a84a"), "h": R("#ffe0a0")}, "h", "Tropical Smoothie"),
    "hot_cocoa": ("bottle", {"g": GLASS, "c": CORK, "l": R("#6a3a1e"), "h": R("#c89a6a")}, "h", "Hot Cocoa"),
    "salmagundi": ("bowl", {"w": BOWL, "f": R("#c8a060"), "g": R("#c83a4a")}, "g", "Salmagundi"),
    "grog_glazed_pork": ("plate", {"a": R("#b85a3a"), "A": R("#e8904a"), "b": R("#d8a040"), "B": R("#f6c86a"), "p": PLATE, "P": R("#c8c4bc")}, "AB", "Grog-Glazed Pork"),
    "shark_jerky": ("jerky", {"a": R("#7a4a3a"), "A": R("#a86a50"), "b": R("#6a3a2a"), "B": R("#9a5a40")}, "", "Shark Jerky"),
    "shark_fin_soup": ("bowl", {"w": BOWL, "f": R("#c8b48a"), "g": R("#6a7a8a")}, "g", "Shark Fin Soup"),
    "fish_and_chips": ("plate", {"a": R("#d8a040"), "A": R("#f0c86a"), "b": R("#f0dc8a"), "B": R("#fff4c0"), "p": R("#e8e0d0"), "P": R("#b8b0a0")}, "AB", "Fish and Chips"),
    "crab_cakes": ("cakes", {"c": R("#c8783a"), "d": R("#e8a860")}, "d", "Crab Cakes"),
    "seafood_boil": ("bowl", {"w": BOWL, "f": R("#e0843a"), "g": R("#c8302a")}, "g", "Seafood Boil"),
    "lobster_thermidor": ("bowl", {"w": BOWL, "f": R("#f0d8a0"), "g": R("#d8402a")}, "g", "Lobster Thermidor"),
    "kraken_ink_pasta": ("bowl", {"w": BOWL, "f": R("#2a2230"), "g": R("#8a6ac8")}, "g", "Kraken Ink Pasta"),
    "grilled_pineapple": ("slice", {"a": R("#e8c040"), "f": R("#a86a2a"), "t": R("#f6de6a")}, "t", "Grilled Pineapple"),
    "pineapple_upside_down_cake": ("slice", {"a": R("#e8c078"), "f": R("#f6d040"), "t": R("#c86a2a")}, "t", "Pineapple Upside-Down Cake"),
    "pineapple_salsa": ("bowl", {"w": BOWL, "f": R("#f0c840"), "g": R("#c8302a")}, "g", "Pineapple Salsa"),
    "key_lime_pie": ("pie", {"c": CRUST, "C": R("#a8783a"), "f": R("#c8e880"), "t": R("#f8fff0")}, "t", "Key Lime Pie"),
    "limeade": ("bottle", {"g": GLASS, "c": CORK, "l": R("#a8e05a"), "h": R("#e0ffb0")}, "h", "Limeade"),
    "scurvy_tonic": ("bottle", {"g": GLASS, "c": CORK, "l": R("#6ab85a"), "h": R("#c8f0a0")}, "h", "Scurvy Tonic"),
    "fire_roasted_chili": ("jerky", {"a": R("#b82a1a"), "A": R("#e85a3a"), "b": R("#3a5a1a"), "B": R("#5a7a2a")}, "", "Fire-Roasted Chili"),
    "chili_con_shark": ("bowl", {"w": BOWL, "f": R("#a8301e"), "g": R("#f0c060")}, "g", "Chili con Shark"),
    "coconut_curry": ("bowl", {"w": BOWL, "f": R("#e8a830"), "g": R("#3a8a3a")}, "g", "Coconut Curry"),
    "blackened_fillet": ("fillet", {"a": R("#c8783a"), "A": R("#e8a060"), "b": R("#3a2418")}, "A", "Blackened Fillet"),
    "fish_taco": ("taco", {"a": R("#e8c070"), "A": R("#f6dc9a"), "b": R("#6aa83a"), "c": R("#e0a060")}, "A", "Fish Taco"),
    "rum_cake": ("slice", {"a": R("#a8683a"), "f": R("#6a3a1e"), "t": R("#e8b85a")}, "t", "Rum Cake"),
    "molasses_cookie": ("cookie", {"c": R("#7a4a22"), "d": R("#3a2010")}, "", "Molasses Cookie"),
    "parrotfish_poke": ("bowl", {"w": BOWL, "f": R("#e8807a"), "g": R("#3ab8a8")}, "g", "Parrotfish Poke"),
    "mahi_pineapple_skewer": ("skewer", {"s": STICK, "a": R("#e8a070"), "A": R("#f6c8a0"), "b": R("#e8c040"), "B": R("#f6de6a")}, "AB", "Mahi-Mahi & Pineapple Skewer"),
    "moonfish_sashimi": ("plate", {"a": R("#e8e4f4"), "A": R("#ffffff"), "b": R("#3a6a3a"), "B": R("#5a8a4a"), "p": R("#2a2a3a"), "P": R("#4a4a5a")}, "A", "Moonfish Sashimi"),
    "ember_eel_skewer": ("skewer", {"s": STICK, "a": R("#c8401e"), "A": R("#f6803a"), "b": R("#6a2a1a"), "B": R("#a8401e")}, "A", "Ember Eel Skewer"),
    "ghostfin_broth": ("bowl", {"w": BOWL, "f": R("#b8e8e0", 1.1, 0.8), "g": R("#e8fffa")}, "g", "Ghostfin Broth"),
    "bone_broth": ("bowl", {"w": BOWL, "f": R("#d8ccb0"), "g": R("#f4f0e4")}, "g", "Bone Broth"),
    "anglerfry_chowder": ("bowl", {"w": BOWL, "f": R("#e8e0c8"), "g": R("#6ae8ff")}, "g", "Anglerfry Chowder"),
    "voidfin_roe": ("jar", {"g": GLASS, "c": CORK, "l": R("#2a1a4a"), "d": R("#b88aff")}, "d", "Voidfin Roe"),
    # --- phase materials (2026-10-01) ---
    "cooked_lava_crab_claw": ("fillet", {"a": R("#c8401e"), "A": R("#f6904a"), "b": R("#3a1a12")}, "A", "Cooked Lava Crab Claw"),
    "cinder_chili_sauce": ("bottle", {"g": GLASS, "c": CORK, "l": R("#d8401e"), "h": R("#f6c040")}, "h", "Cinder Chili Sauce"),
    "brimstone_smoked_fish": ("fillet", {"a": R("#b8862a"), "A": R("#e8c05a"), "b": R("#4a3010")}, "A", "Brimstone-Smoked Fish"),
    "ghostly_brew": ("bottle", {"g": GLASS, "c": CORK, "l": R("#7ae8a0", 1.2, 0.75), "h": R("#e0fff0")}, "h", "Ghostly Brew"),
    "bone_marrow_broth": ("bowl", {"w": BOWL, "f": R("#c8bca0"), "g": R("#5ad87a")}, "g", "Bone Marrow Broth"),
    "luminous_draught": ("bottle", {"g": GLASS, "c": CORK, "l": R("#3af0d0", 1.2, 0.7), "h": R("#e0fff8")}, "h", "Luminous Draught"),
    "whales_bounty": ("plate", {"a": R("#e88a8a"), "A": R("#f6c0b0"), "b": R("#3a8a6a"), "B": R("#6ac8a0"), "p": PLATE, "P": R("#c8c4bc")}, "AB", "Whale's Bounty"),
    # --- boss signature dishes ---
    "rackhams_reserve": ("bottle", {"g": R("#4a3a2a", 1.2, 0.7), "c": R("#c8302a"), "l": R("#8a4a1a"), "h": R("#e8a040")}, "h", "Rackham's Reserve"),
    "serpent_steak": ("plate", {"a": R("#1e8a8a"), "A": R("#4ad0c0"), "b": R("#c84a3a"), "B": R("#f0805a"), "p": PLATE, "P": R("#c8c4bc")}, "AB", "Serpent Steak"),
    "molten_core_chili": ("bowl", {"w": R("#3a3030"), "f": R("#e0501e"), "g": R("#ffd040")}, "g", "Molten Core Chili"),
    "phantom_hardtack": ("cookie", {"c": R("#b8d8c8", 1.1, 0.75), "d": R("#5a8a7a")}, "d", "Phantom Hardtack"),
    "royal_tide_feast": ("plate", {"a": R("#e0b040"), "A": R("#ffe080"), "b": R("#2a8a8a"), "B": R("#5ad0c8"), "p": R("#2a5a6a"), "P": R("#1a3a4a")}, "AB", "Royal Tide Feast"),
    "bloodfin_fillet": ("fillet", {"a": R("#8a1a1a"), "A": R("#d84a4a"), "b": R("#3a0a0a")}, "A", "Bloodfin Fillet"),
    "kraken_platter": ("plate", {"a": R("#7a3a8a"), "A": R("#c07ad0"), "b": R("#e8c070"), "B": R("#fff0b0"), "p": PLATE, "P": R("#c8c4bc")}, "AB", "Kraken Platter"),
    "last_meal": ("plate", {"a": R("#6a6a5a"), "A": R("#a8a890"), "b": R("#4a3a2a"), "B": R("#7a5a3a"), "p": R("#3a3a40"), "P": R("#2a2a30")}, "AB", "The Last Meal"),
    "heart_tartare": ("plate", {"a": R("#7a1424"), "A": R("#c8404a"), "b": R("#e8c070"), "B": R("#fff0b0"), "p": PLATE, "P": R("#c8c4bc")}, "AB", "Heart Tartare"),
    "leviathan_steak": ("plate", {"a": R("#1a2a3a"), "A": R("#4a6a8a"), "b": R("#c8302a"), "B": R("#f0705a"), "p": R("#2a2a3a"), "P": R("#4a4a5a")}, "AB", "Leviathan Steak"),
}


def main():
    sheet = Image.new("RGBA", (16 * 10, 16 * ((len(DISHES) + 9) // 10)), (48, 48, 52, 255))
    for i, (did, (tpl, pal, flat, _)) in enumerate(DISHES.items()):
        img = g.sprite(T[tpl], pal, flat=flat)
        g.save(img, g.ITEM, did)
        sheet.alpha_composite(img.convert("RGBA"), ((i % 10) * 16, (i // 10) * 16))
    out = ROOT / "tools/previews"
    out.mkdir(parents=True, exist_ok=True)
    sheet.resize((sheet.width * 6, sheet.height * 6), Image.NEAREST).save(out / "food_sheet.png")
    d = json.loads(LANG.read_text(encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
    for did, (*_, name) in DISHES.items():
        d["item.pixelpirates." + did] = name
    LANG.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(len(DISHES), "dishes; preview tools/previews/food_sheet.png")


if __name__ == "__main__":
    main()
