"""Phase materials + gadgets (Materials & Gear Ladder design, 2026-10-01): item textures + English names.

    python tools/gen_material_textures.py   -> textures/item/<id>.png, lang entries, tools/previews/material_sheet.png

16x16 char grids drawn by gen_overhaul_textures.sprite() (top-left lighting + dark outline), like every other icon.
Ids must match ModItems.
"""
import json, collections, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import gen_overhaul_textures as g
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANG = ROOT / "src/main/resources/assets/pixelpirates/lang/en_us.json"
R = g.ramp

BOX = ['................', '................', '................', '...bbbbbbbbbb...', '..bwwwwiwwwwwb..', '..bwwwwiwwwwwb..', '..biiiiiiiiiib..', '..bwwwwlLwwwwb..', '..bwwwwLlwwwwb..', '..bwwwwiwwwwwb..', '..bwwwwiwwwwwb..', '..biiiiiiiiiib..', '..bbbbbbbbbbbb..', '................', '................', '................']

ITEMS = {
    "crab_shell": ("Crab Shell", {"o": R("#8a2a14"), "O": R("#d8582a"), "h": R("#f6a060")}, "h", [
        "................",
        "................",
        "................",
        ".....oooooo.....",
        "...ooOOOOOOoo...",
        "..oOOhOOOOhOOo..",
        "..oOOOOOOOOOOo..",
        ".oOOhOOOOOOhOOo.",
        ".oOOOOOhhOOOOOo.",
        ".oOOOOOOOOOOOOo.",
        "..oOOhOOOOhOOo..",
        "..ooOOOOOOOOoo..",
        "....oooooooo....",
        "................",
        "................",
        "................"]),
    "siren_scale": ("Siren Scale", {"s": R("#1e8a8a"), "t": R("#4ad0c0"), "h": R("#c8fff0"), "v": R("#7a5ac8")}, "h", [
        "................",
        "................",
        ".......ss.......",
        "......sTTs......",
        ".....sTttTs.....",
        ".....stthts.....",
        "....sttthtts....",
        "....stttttts....",
        "....svtttttvs...",
        "....svvtttvvs...",
        ".....svvvvvs....",
        ".....ssvvvss....",
        "......ssss......",
        "................",
        "................",
        "................"]),
    "reef_pearl": ("Reef Pearl", {"p": R("#e8d8e0"), "h": R("#ffffff"), "k": R("#e07a8a"), "K": R("#b84a5a")}, "h", [
        "................",
        "................",
        "................",
        "................",
        "......pppp......",
        ".....pphhpp.....",
        "....pphhpppp....",
        "....pphppppp....",
        "....pppppppp....",
        ".....pppppp.....",
        "...kk.pppp.kk...",
        "..kKKk....kKKk..",
        "...kKKkkkkKKk...",
        ".....kkkkkk.....",
        "................",
        "................"]),
    "brimstone": ("Brimstone", {"y": R("#d8b020"), "Y": R("#f6e05a"), "o": R("#8a6a10")}, "", [
        "................",
        "................",
        "................",
        ".......YY.......",
        "......YyyY......",
        "....YYyyyyo.....",
        "...YyyyYyyyo....",
        "...yyyYYyyyyo...",
        "..YyyyyyyyYyo...",
        "..yyyyYyyyyyyo..",
        "...yyyyyyyyyo...",
        "....oyyyyyyoo...",
        ".....oooooo.....",
        "................",
        "................",
        "................"]),
    "obsidian_shard": ("Obsidian Shard", {"b": R("#1a1028"), "p": R("#5a2a8a"), "h": R("#b080f0")}, "h", [
        "................",
        "...........bb...",
        "..........bpb...",
        ".........bphb...",
        "........bpbb....",
        ".......bphb.....",
        "......bpbb......",
        ".....bphb.......",
        "....bpbb........",
        "...bphb.........",
        "...bbb..........",
        "..bb............",
        "................",
        "................",
        "................",
        "................"]),
    "ectoplasm": ("Ectoplasm", {"e": R("#5ad87a", 1.2, 0.7), "h": R("#d0ffd8"), "d": R("#2a8a4a")}, "h", [
        "................",
        "................",
        "................",
        "......eeee......",
        "....eeeeeeee....",
        "...eeheeeeeee...",
        "...ehheeeeeee...",
        "..eeeeeeeeeeee..",
        "..eeeeeeeeeeee..",
        "...eeeeeeeeee...",
        "....eedeeede....",
        ".....d..e..d....",
        ".....d.....d....",
        "................",
        "................",
        "................"]),
    "lost_soul": ("Lost Soul", {"w": R("#8ae8f0", 1.25, 0.7), "c": R("#d8ffff"), "k": (24, 40, 56)}, "k", [
        "................",
        ".......w........",
        "......ww........",
        "......wcw.......",
        ".....wcccw......",
        ".....wcccww.....",
        "....wcckckcw....",
        "....wccccccw....",
        "....wcckkccw....",
        ".....wccccw.....",
        ".....wccccw.....",
        "......wccw......",
        "......w.ww......",
        ".....w...w......",
        "................",
        "................"]),
    "abyssal_pearl": ("Abyssal Pearl", {"p": R("#1e2a6a"), "g": R("#3ad8f0"), "h": R("#c8ffff")}, "h", [
        "................",
        "................",
        "................",
        "................",
        "......pppp......",
        ".....pppppp.....",
        "....ppgggppp....",
        "....pgghgppp....",
        "....pgggppp.....",
        "....pppppppp....",
        ".....pppppp.....",
        "......pppp......",
        "................",
        "................",
        "................",
        "................"]),
    "luminous_ichor": ("Luminous Ichor", {"g": R("#b8d8e0", 1.1, 0.75), "c": R("#8a6a42"), "l": R("#3af0d0", 1.2, 0.7), "h": R("#e0fff8")}, "h", [
        "................",
        "......cc........",
        "......cc........",
        ".....gggg.......",
        "......gg........",
        ".....gllg.......",
        "....glllhg......",
        "...gllllllg.....",
        "...gllhllllg....",
        "...glllllllg....",
        "...glllllllg....",
        "....gllllllg....",
        ".....gggggg.....",
        "................",
        "................",
        "................"]),
    "krill_cluster": ("Krill Cluster", {"k": R("#e88a8a"), "K": R("#f6c0b0"), "e": (30, 20, 20)}, "e", [
        "................",
        "................",
        "................",
        "....kk....kk....",
        "...kKKe..kKKe...",
        "..kKKk..kKKk....",
        "..kkk...kkk.....",
        ".....kk.....kk..",
        "....kKKe...kKKe.",
        "...kKKk...kKKk..",
        "...kkk....kkk...",
        "......kk........",
        ".....kKKe.......",
        "....kKKk........",
        "....kkk.........",
        "................"]),
    "tidal_core": ("Tidal Core", {"r": R("#c8a040"), "b": R("#1e5a9a"), "t": R("#3ac8e0"), "h": R("#e0ffff")}, "h", [
        "................",
        "................",
        ".....rrrrrr.....",
        "....rbbbbbbr....",
        "...rbbttbbbbr...",
        "..rbbtbbtbbbbr..",
        "..rbtbbbbtbbbr..",
        "..rbtbbhbbtbbr..",
        "..rbbtbbbbtbbr..",
        "..rbbbtbbtbbbr..",
        "...rbbbttbbbr...",
        "....rbbbbbbr....",
        ".....rrrrrr.....",
        "................",
        "................",
        "................"]),
    "raw_lava_crab_claw": ("Raw Lava Crab Claw", {"a": R("#2a1a1a"), "r": R("#c8301e"), "o": R("#f6803a")}, "o", [
        "................",
        "................",
        "......rrr.......",
        ".....rrrrr..rr..",
        "....rrorrr.rrr..",
        "....rrr...rrrr..",
        "....rrr..rrrr...",
        "....rrrrrrrr....",
        ".....rrrrrr.....",
        "......aarr......",
        ".....aaaa.......",
        "....aaaa........",
        "...aaa..........",
        "................",
        "................",
        "................"]),
    "siren_conch": ("Siren's Conch", {"c": R("#f0d8c0"), "p": R("#e890a0"), "s": R("#a87a6a")}, "", [
        "................",
        "................",
        "..........cc....",
        ".........cccc...",
        "........ccsccc..",
        "......ccccsccc..",
        "....ccccccsscc..",
        "...cccccscccc...",
        "..ppcccsccccc...",
        "..pppccscccc....",
        "...pppcccccc....",
        "....pppcccc.....",
        "......pppp......",
        "................",
        "................",
        "................"]),
    "ink_bomb": ("Ink Bomb", {"b": R("#1a1424"), "v": R("#6a4a9a"), "c": R("#8a6a42"), "f": R("#c8a060")}, "f", [
        "................",
        ".........f......",
        "........f.......",
        "......cc........",
        "......cc........",
        ".....bbbb.......",
        "....bbbbbb......",
        "...bbvbbbbb.....",
        "...bvbbbbbb.....",
        "...bbbbbbbb.....",
        "...bbbbbbbb.....",
        "....bbbbbb......",
        ".....bbbb.......",
        "................",
        "................",
        "................"]),
    "shell_buckler": ("Shell Buckler", {"w": R("#6a4a2a"), "o": R("#d8582a"), "h": R("#f6a060"), "m": R("#c8a060")}, "m", [
        "................",
        ".....wwwwww.....",
        "....wooooooww...",
        "...woohoooooww..",
        "..wooooooooooww.",
        "..woohooohoooow.",
        "..wooooommoooow.",
        "..woooommmmooow.",
        "..wooooommoooow.",
        "..woohoooooohow.",
        "..wwooooooooww..",
        "...wwoooooooww..",
        "....wwwwwwww....",
        "................",
        "................",
        "................"]),
    "common_strongbox": ("Common Strongbox", {"b": R("#3a2410"), "w": R("#8a5a30"), "i": R("#7a7a80"), "l": R("#c8c8d0"), "L": R("#5a5a60")}, "lL", BOX),
    "rare_strongbox": ("Rare Strongbox", {"b": R("#1a0e08"), "w": R("#4a2a18"), "i": R("#c8a040"), "l": R("#ffe08a"), "L": R("#8a6a14")}, "lL", BOX),
    "legendary_strongbox": ("Legendary Strongbox", {"b": R("#0a0a14"), "w": R("#1e1e3a"), "i": R("#3ad8e0", 1.2, 0.7), "l": R("#e0ffff"), "L": R("#1a8a9a")}, "lL", BOX),
}


def main():
    sheet = Image.new("RGBA", (16 * 8, 16 * ((len(ITEMS) + 7) // 8)), (48, 48, 52, 255))
    for i, (iid, (_, pal, flat, rows)) in enumerate(ITEMS.items()):
        img = g.sprite(rows, pal, flat=flat)
        g.save(img, g.ITEM, iid)
        sheet.alpha_composite(img.convert("RGBA"), ((i % 8) * 16, (i // 8) * 16))
    out = ROOT / "tools/previews"
    out.mkdir(parents=True, exist_ok=True)
    sheet.resize((sheet.width * 6, sheet.height * 6), Image.NEAREST).save(out / "material_sheet.png")
    d = json.loads(LANG.read_text(encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
    for iid, (name, *_) in ITEMS.items():
        d["item.pixelpirates." + iid] = name
    LANG.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(len(ITEMS), "items; preview tools/previews/material_sheet.png")


if __name__ == "__main__":
    main()
